title: Site

fields:
  title:
    label: Title
    type:  text

  open_days:
    label: Days
    type:  text
    width: 1/4	

  open_hours:
    label: Hours
    type:  text
    width: 1/4

  address:
    label: Address
    type:  textarea

  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea
    
  copyright:
    label: Copyright
    type:  textarea

